### PR TITLE
feat: TS-14025 Bump ampqlib

### PR DESCRIPTION
**Pull request by ten-als**
## Types of changes

- [ ] Documentation only (no changes to either `lib/` or `test/` files)
- [ ] Bug fix (non-breaking change which fixes an issue. you didn't modify existing tests)
- [ ] New feature (non-breaking change which adds functionality. you added at least one new test)
- [ ] Breaking change (fix or feature that would cause existing functionality to change. you had to modify existing tests.)

## Checklist:

- [ ] I have read the [**CONTRIBUTING**](https://github.com/tenna-llc/bunnybus/blob/master/.github/CONTRIBUTING.md) document.
- [ ] My code follows the [Hapi.js style guide](https://github.com/hapijs/contrib/blob/master/Style.md).
- [ ] I have updated the documentation as needed.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by ten-jwj** [comment]
It's interesting that this is going into v6 and not main.. are these two changes already on the main branch but not as atomic commits that can get picked over? Heck of a time to try to move this task forward with @ten-ceh on PTO through the new year- there's a deliberate effort not to introduce these breaking behavioral changes on patch versions because of the instability it could introduce.

**Comment by ten-als** [comment]
@ten-jwj I wanted to publish 6.7.1 for older services like be-crud with just ampqlib updates but I am absolutely losing my mind with tests failing for no reason even with the old version. I will see if updating be-crud to v7 is easier...

**Comment by ten-jwj** [comment]
That's probably the path of least resistance. Also worth noting that there's an experimental V8 of this, currently on 8.0.0-1, but we haven't finalized that change yet, so there's no released V8. I'd try walking forward with one of those two to get the amqplib dependency fixed. I'm not totally opposed to patching v6, I just want to be extra careful about it, and I think the test hell you're hitting is a dead end that made us walk this up to v7/V8 in the first place.

**Comment by ten-als** [comment]
@ten-jwj I thought about it but it causes peer deps issues with ingestion pipeline and I just wanna get rid of those errors. V8 looks like a drop in replacement with just runtime changes so shouldn't be too hard.

**Pull request closed without merging**
